jms_translation:
    configs:
        victoire_widget_socialbuttons_bundle:
            dirs: ["@VictoireWidgetSocialButtonsBundle"]
            output_dir: "src/Victoire/Widget/SocialButtonsBundle/Resources/translations"

victoire_core:
    widgets:
        SocialButtons:
            class: "Victoire\\Widget\\SocialButtonsBundle\\Entity\\WidgetSocialButtons"
            name: SocialButtons
