services:

    victoire_core.widget_socialbuttons_content_resolver:
        class: Victoire\Widget\ListingBundle\Resolver\WidgetListingContentResolver
        parent: victoire_core.widget_listing_content_resolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: SocialButtons }

    victoire.widget.socialbuttons:
        class: Victoire\Widget\SocialButtonsBundle\Entity\WidgetSocialButtons

    victoire.widget.form.socialbuttons:
        class: Victoire\Widget\SocialButtonsBundle\Form\WidgetSocialButtonsType
        tags:
            - { name: form.type }
